CREATE TABLE IF NOT EXISTS district_stats (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    district_code VARCHAR(10) NOT NULL,
    district_name VARCHAR(20),
    quarter TINYINT NOT NULL,
    year SMALLINT NOT NULL,
    foot_traffic BIGINT,
    foot_traffic_delta DECIMAL(12, 6),
    foot_traffic_gap BIGINT,
    sales_amount BIGINT,
    sales_delta DECIMAL(12, 6),
    sales_gap BIGINT,
    store_count INT,
    store_count_delta DECIMAL(12, 6),
    store_count_gap BIGINT,
    closure_rate DECIMAL(12, 6),
    closure_rate_delta DECIMAL(12, 6),
    closure_rate_gap BIGINT,
    rent_amount DECIMAL(12, 2),
    rent_delta DECIMAL(12, 6),
    rent_gap DECIMAL(12, 2),
    vacancy_rate DECIMAL(12, 6),
    vacancy_rate_delta DECIMAL(12, 6),
    vacancy_rate_gap DECIMAL(12, 2),
    decline_grade VARCHAR(1),
    direction VARCHAR(10),
    composite_score DECIMAL(12, 6),
    avg_operating_years DECIMAL(5, 2),
    INDEX idx_district_stats_year_quarter (year, quarter),
    INDEX idx_district_stats_district_code (district_code)
);
